# Generated by Django 5.1.6 on 2025-04-05 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Enter a valid phone number')], verbose_name='phone number'),
        ),
    ]
