# Generated by Django 5.1.6 on 2025-03-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_id_alter_book_id_alter_publisher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='status',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='status',
            new_name='Active',
        ),
    ]
