# Generated by Django 5.1.6 on 2025-03-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_options_rename_active_author_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.TextField(default='/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url',
            field=models.TextField(default='/'),
        ),
    ]
