# Generated by Django 5.1.6 on 2025-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_author_url_alter_publisher_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='books/'),
        ),
    ]
